### ISSUE TITLE
maquette en cours / tableau de bord : indicateurs economiques

### ISSUE THREAD

**Issue by eheliot12** [endi-entreprendre-differemment/maquette-enDI#4]
faire apparaitre un ou 2 indicateurs sous forme de jauge : niveau a atteindre, niveau en cours. on peut parler en CA ou salaire, ainsi qu'en nb de devis ou facture.

**Comment by SophieWeb** [comment]
Dispo sur la maquette.

**Comment by eheliot12** [comment]
ok
