### ISSUE TITLE
maquette en cours / calendrier / evenements de gestion 

### ISSUE THREAD

**Issue by eheliot12** [endi-entreprendre-differemment/maquette-enDI#5]
ajouter a titre d'exemple
* des evenements de gestion. par exemple date limite pour sa note de frais ou ses remises cheques
* des periodes d'indispo des EA, par exemple cloture annuel

au dela de la liste chronologique
* le top de la semaine et le top de la semaine suivante

**Comment by SophieWeb** [comment]
C’est dispo pour les deux exemples.

Pour les tops, quel genre de contenu ce serait ?

**Comment by SophieWeb** [comment]
J’ai fait une proposition, à voir.

**Comment by eheliot12** [comment]
ok, pour l'usage maquette me va
