### ISSUE TITLE
presentation ecran / effet demo

### ISSUE THREAD

**Issue by eheliot12** [endi-entreprendre-differemment/maquette-enDI#7]
si je peux avoir un petit changement d'ordre 

favori - indicateur eco 
calendrier - document
transaction - vie CAE

ajout d'un cadre d'info vraiment externe, on pourrait croire que vie CAE c'est des infos rentrees dans endi
la meteo c'est un peu niais, un mur agrege linkedin ou facebook ?

**Comment by SophieWeb** [comment]
J’ai changé l’ordre, changé l’icône de Vie de la CAE pour que ça ait moins l’air d’une messagerie, et ajouté le bloc LinkedIn.

**Comment by eheliot12** [comment]
super
j'imagine que l'espace blanc sous les indicateurs n'est pas diminuable dans ce mode maquette rapide.

faudrait trouver un autre indicateur : tresorerie avec le montant ?

**Comment by eheliot12** [comment]
avec le repliage du menu le favoris se mettent sur une ligne donc ok pas besoin
